#include "assetManager.h"

#include "../../assets/JugadorGolem/estado-moviendose-abajo/JGMA.h"
#include "../../assets/JugadorGolem/estado-moviendose-arriba/JGMUp.h"
#include "../../assets/JugadorGolem/estado-moviendose-lados/JGML.h"
#include "../../assets/JugadorGolem/estado-reposo/JGT.h"

#include "../../assets/menu/botonExit.h"
#include "../../assets/menu/botonExitSelec.h"
#include "../../assets/menu/botonExtra.h"
#include "../../assets/menu/botonExtraSelec.h"
#include "../../assets/menu/botonPlay.h"
#include "../../assets/menu/botonPlaySelec.h"
#include "../../assets/menu/dibujoFondoMenu.h"
#include "../../assets/menu/dificil.h"
#include "../../assets/menu/dificilSeleccionado.h"
#include "../../assets/menu/facil.h"
#include "../../assets/menu/facilSeleccionado.h"
#include "../../assets/menu/tituloJuego.h"

#include "../../assets/minijuegoAutotronica/bateriaE1.h"
#include "../../assets/minijuegoAutotronica/bateriaE2.h"
#include "../../assets/minijuegoAutotronica/bateriaE3.h"
#include "../../assets/minijuegoAutotronica/cajaRepuestos.h"
#include "../../assets/minijuegoAutotronica/carro.h"
#include "../../assets/minijuegoAutotronica/energia.h"
#include "../../assets/minijuegoAutotronica/frenoE1.h"
#include "../../assets/minijuegoAutotronica/frenoE2.h"
#include "../../assets/minijuegoAutotronica/frenoE3.h"
#include "../../assets/minijuegoAutotronica/fusible.h"
#include "../../assets/minijuegoAutotronica/llaveInglesa.h"
#include "../../assets/minijuegoAutotronica/lucesE1.h"
#include "../../assets/minijuegoAutotronica/lucesE2.h"
#include "../../assets/minijuegoAutotronica/lucesE3.h"
#include "../../assets/minijuegoAutotronica/silenciadorE1.h"
#include "../../assets/minijuegoAutotronica/silenciadorE2.h"
#include "../../assets/minijuegoAutotronica/silenciadorE3.h"

#include "../../assets/minijuegoDisenoArquitectonico/contorno.h"
#include "../../assets/minijuegoDisenoArquitectonico/pieza1.h"
#include "../../assets/minijuegoDisenoArquitectonico/pieza2.h"
#include "../../assets/minijuegoDisenoArquitectonico/pieza3.h"
#include "../../assets/minijuegoDisenoArquitectonico/pieza4.h"
#include "../../assets/minijuegoDisenoArquitectonico/pieza5.h"
#include "../../assets/minijuegoDisenoArquitectonico/pieza6.h"
#include "../../assets/minijuegoDisenoArquitectonico/pieza7.h"
#include "../../assets/minijuegoDisenoArquitectonico/pieza8.h"

#include "../../assets/minijuegoElectronicaYControl/chasis.h"
#include "../../assets/minijuegoElectronicaYControl/puntero.h"
#include "../../assets/minijuegoElectronicaYControl/soporte.h"

#include "../../assets/minijuegoMecanicaIndustrial/cinta1.h"
#include "../../assets/minijuegoMecanicaIndustrial/cinta2.h"
#include "../../assets/minijuegoMecanicaIndustrial/cinta3.h"
#include "../../assets/minijuegoMecanicaIndustrial/cinta4.h"
#include "../../assets/minijuegoMecanicaIndustrial/cinta5.h"
#include "../../assets/minijuegoMecanicaIndustrial/cinta6.h"
#include "../../assets/minijuegoMecanicaIndustrial/cinta7.h"
#include "../../assets/minijuegoMecanicaIndustrial/cintas.h"
#include "../../assets/minijuegoMecanicaIndustrial/corazon.h"
#include "../../assets/minijuegoMecanicaIndustrial/L.h"
#include "../../assets/minijuegoMecanicaIndustrial/LM.h"
#include "../../assets/minijuegoMecanicaIndustrial/pantalla.h"
#include "../../assets/minijuegoMecanicaIndustrial/pistonActivado.h"
#include "../../assets/minijuegoMecanicaIndustrial/pistonDesActivado.h"
#include "../../assets/minijuegoMecanicaIndustrial/T.h"
#include "../../assets/minijuegoMecanicaIndustrial/TM.h"
#include "../../assets/minijuegoMecanicaIndustrial/Z.h"
#include "../../assets/minijuegoMecanicaIndustrial/ZM.h"

#include "../../assets/minijuegoMecatronica/apagado.h"
#include "../../assets/minijuegoMecatronica/azulM.h"
#include "../../assets/minijuegoMecatronica/bateria.h"
#include "../../assets/minijuegoMecatronica/botella.h"
#include "../../assets/minijuegoMecatronica/caja.h"
#include "../../assets/minijuegoMecatronica/caneca1.h"
#include "../../assets/minijuegoMecatronica/caneca2.h"
#include "../../assets/minijuegoMecatronica/caneca3.h"
#include "../../assets/minijuegoMecatronica/caneca4.h"
#include "../../assets/minijuegoMecatronica/cascara.h"
#include "../../assets/minijuegoMecatronica/garra.h"
#include "../../assets/minijuegoMecatronica/lata.h"
#include "../../assets/minijuegoMecatronica/lente.h"
#include "../../assets/minijuegoMecatronica/palo.h"
#include "../../assets/minijuegoMecatronica/rojo.h"
#include "../../assets/minijuegoMecatronica/verdeM.h"

#include "../../assets/minijuegoPagina/carrito.h"
#include "../../assets/minijuegoPagina/compraAzul.h"
#include "../../assets/minijuegoPagina/contornoWeb.h"
#include "../../assets/minijuegoPagina/imagen.h"
#include "../../assets/minijuegoPagina/lupa.h"
#include "../../assets/minijuegoPagina/menu.h"
#include "../../assets/minijuegoPagina/texto.h"
#include "../../assets/minijuegoPagina/titulo.h"
#include "../../assets/minijuegoPagina/compraRojo.h"


#include "../../assets/minijuegoPonchar/azul.h"
#include "../../assets/minijuegoPonchar/azulBlanco.h"
#include "../../assets/minijuegoPonchar/cafe.h"
#include "../../assets/minijuegoPonchar/cafeBlanco.h"
#include "../../assets/minijuegoPonchar/naranja.h"
#include "../../assets/minijuegoPonchar/naranjaBlanco.h"
#include "../../assets/minijuegoPonchar/pObjetivo.h"
#include "../../assets/minijuegoPonchar/rj-45.h"
#include "../../assets/minijuegoPonchar/verde.h"
#include "../../assets/minijuegoPonchar/verdeBlanco.h"

#include "../../assets/minijuegoRedes/click.h"
#include "../../assets/minijuegoRedes/flecha.h"
#include "../../assets/minijuegoRedes/tipoCruz.h"
#include "../../assets/minijuegoRedes/tipoCruzI.h"
#include "../../assets/minijuegoRedes/tipoInterseccion.h"
#include "../../assets/minijuegoRedes/tipoInterseccionI.h"
#include "../../assets/minijuegoRedes/tipoL.h"
#include "../../assets/minijuegoRedes/tipoLI.h"
#include "../../assets/minijuegoRedes/tipoLinea.h"
#include "../../assets/minijuegoRedes/tipoLineaI.h"

#include "../../assets/minijuegoSoldadura/panelSoldar1.h"
#include "../../assets/minijuegoSoldadura/panelSoldar2.h"
#include "../../assets/minijuegoSoldadura/panelSoldar3.h"
#include "../../assets/minijuegoSoldadura/panelSoldar4.h"
#include "../../assets/minijuegoSoldadura/panelSoldar5.h"
#include "../../assets/minijuegoSoldadura/pulidora.h"
#include "../../assets/minijuegoSoldadura/soldaduraLimpia.h"
#include "../../assets/minijuegoSoldadura/soldaduraSucia.h"
#include "../../assets/minijuegoSoldadura/sopleteActivado.h"
#include "../../assets/minijuegoSoldadura/sopleteDesactivado.h"

#include "../../assets/nexusxd/fondoNexus.h"
#include "../../assets/nexusxd/puertaBase.h"
#include "../../assets/nexusxd/puertaDiseno3.h"
#include "../../assets/nexusxd/puertaDiseno.h"
#include "../../assets/nexusxd/puertaElectricidad.h"
#include "../../assets/nexusxd/puertaElectricidad2.h"
#include "../../assets/nexusxd/puertaInformatica.h"
#include "../../assets/nexusxd/puertaInformatica1.h"
#include "../../assets/nexusxd/puertaMetalmecanica.h"
#include "../../assets/nexusxd/puertaMetalmecanica4.h"

#include "../../assets/pantallaCarga/imagenDefault.h"
#include "../../assets/pantallaCarga/imagenDiseno.h"
#include "../../assets/pantallaCarga/imagenElectricidad.h"
#include "../../assets/pantallaCarga/imagenInformatica.h"
#include "../../assets/pantallaCarga/imagenMetalmecanica.h"
#include "../../assets/pantallaCarga/minijuegoAutotronica.h"
#include "../../assets/pantallaCarga/minijuegoDisenoArquitectonico.h"
#include "../../assets/pantallaCarga/minijuegoDisenoComputador.h"
#include "../../assets/pantallaCarga/minijuegoElectronicaYControl.h"
#include "../../assets/pantallaCarga/minijuegoMecanicaIndustrial.h"
#include "../../assets/pantallaCarga/minijuegoMecatronica.h"
#include "../../assets/pantallaCarga/minijuegoPonchar.h"
#include "../../assets/pantallaCarga/minijuegoRedes.h"
#include "../../assets/pantallaCarga/minijuegoSoldadura.h"
#include "../../assets/pantallaCarga/minijuegoTangram.h"
#include "../../assets/pantallaCarga/minijuegoTopografia.h"

#include "../../assets/pantallaCarga/controles/backspace.h"
#include "../../assets/pantallaCarga/controles/enter.h"
#include "../../assets/pantallaCarga/controles/esc.h"
#include "../../assets/pantallaCarga/controles/flechas.h"
#include "../../assets/pantallaCarga/controles/mouse.h"
#include "../../assets/pantallaCarga/controles/space.h"
#include "../../assets/pantallaCarga/controles/wasd.h"

#include "../../assets/textos/Bangers-Regular.h"
#include "../../assets/textos/NotoSans-Regular.h"
#include "../../assets/textos/NotoSans-SemiBold.h"
#include "../../assets/textos/Ubuntu-Bold.h"

#include "../../assets/Topografia/binyeTopo.h"
#include "../../assets/Topografia/linea1.h"
#include "../../assets/Topografia/linea2.h"

#include "../../assets/fondo.h"
#include "../../assets/fondoDiseno.h"
#include "../../assets/fondoElectricidad.h"
#include "../../assets/fondoInformatica.h"
#include "../../assets/fondoMetalmecanica.h"
#include "../../assets/logroDesbloqueado.h"
#include "../../assets/logroDesbloqueadodiseno.h"
#include "../../assets/logroDesbloqueadoelectricidad.h"
#include "../../assets/logroDesbloqueadoinformatica.h"
#include "../../assets/logroDesbloqueadometalmecanica.h"
#include "../../assets/logroDesbloqueadoGeneral.h"

#include "../../assets/musica/musicaCreditos.h"
#include "../../assets/musica/musicaDiseno.h"
#include "../../assets/musica/musicaElectricidad.h"
#include "../../assets/musica/musicaHub.h"
#include "../../assets/musica/musicaInformatica.h"
#include "../../assets/musica/musicaMetalmecanica.h"
#include "../../assets/musica/sonidoLogro.h"
#include "../../assets/musica/sonido1.h"
#include "../../assets/musica/sonido2.h"
#include "../../assets/musica/sonido3.h"
#include "../../assets/musica/sonido4.h"
#include "../../assets/musica/sonido5.h"
#include "../../assets/musica/sonido6.h"
#include "../../assets/musica/sonido7.h"
#include "../../assets/musica/sonido8.h"
#include "../../assets/musica/sonido9.h"

